window.__ANALYTICA_DEMO_REPORT__={
  analysis_id:"demo_packaging_ny_v1",
  business_activity:"Packaging manufacturing",
  geography:"New York",
  market_scope:"United States — R&D fixture",
  status:"COMPLETED",
  readiness_label:"R&D vertical slice — synthetic evidence only",
  disclaimer:"All companies and evidence in this demonstrator are synthetic. No real-company conclusion is being asserted.",
  cohort:{target_size:100,fixture_company_count:5,active_count:1,distressed_count:1,failed_count:1,high_performer_count:2,note:"Production target is up to 100 comparable companies; this fixture intentionally uses five synthetic entities to validate product behavior."},
  evidence:[
    {evidence_id:"ev_northstar_2021_margin",company_id:"cmp_northstar",source_title:"Northstar Packaging synthetic operating note",publisher:"Analytica R&D Fixture",period:2021,fact:"Input costs rose while management delayed new fixed-asset purchases.",confidence:.98},
    {evidence_id:"ev_northstar_2023_mix",company_id:"cmp_northstar",source_title:"Northstar Packaging synthetic product-mix note",publisher:"Analytica R&D Fixture",period:2023,fact:"Higher-margin recyclable film became a larger share of sales.",confidence:.96},
    {evidence_id:"ev_hudson_2020_expansion",company_id:"cmp_hudson",source_title:"Hudson Carton synthetic expansion note",publisher:"Analytica R&D Fixture",period:2020,fact:"Two facilities were opened before utilization recovered.",confidence:.97},
    {evidence_id:"ev_hudson_2022_restructure",company_id:"cmp_hudson",source_title:"Hudson Carton synthetic restructuring note",publisher:"Analytica R&D Fixture",period:2022,fact:"One site was consolidated and equipment moved to leased capacity.",confidence:.95},
    {evidence_id:"ev_empire_2021_customer",company_id:"cmp_empire",source_title:"Empire Flex synthetic concentration note",publisher:"Analytica R&D Fixture",period:2021,fact:"One customer represented an unusually large modeled revenue share.",confidence:.94},
    {evidence_id:"ev_empire_2022_loss",company_id:"cmp_empire",source_title:"Empire Flex synthetic loss event",publisher:"Analytica R&D Fixture",period:2022,fact:"The largest customer contract ended and the synthetic business later closed.",confidence:.99},
    {evidence_id:"ev_liberty_2019_supplier",company_id:"cmp_liberty",source_title:"Liberty Wrap synthetic supplier note",publisher:"Analytica R&D Fixture",period:2019,fact:"The company diversified resin suppliers before a modeled price shock.",confidence:.93},
    {evidence_id:"ev_liberty_2024_automation",company_id:"cmp_liberty",source_title:"Liberty Wrap synthetic automation note",publisher:"Analytica R&D Fixture",period:2024,fact:"Automation was added after sustained utilization exceeded the fixture threshold.",confidence:.95}
  ],
  companies:[
    {company_id:"cmp_northstar",display_name:"Northstar Packaging (synthetic)",status:"high_performer",comparability_score:.94,trajectory:[
      {year:2016,performance_score:58,risk_score:.42,state:"blue",evidence_ids:[]},{year:2017,performance_score:62,risk_score:.38,state:"blue",evidence_ids:[]},{year:2018,performance_score:66,risk_score:.34,state:"blue",evidence_ids:[]},{year:2019,performance_score:70,risk_score:.30,state:"blue",evidence_ids:[]},{year:2020,performance_score:64,risk_score:.36,state:"blue",evidence_ids:[]},{year:2021,performance_score:61,risk_score:.39,state:"blue",evidence_ids:["ev_northstar_2021_margin"]},{year:2022,performance_score:72,risk_score:.28,state:"blue",evidence_ids:[]},{year:2023,performance_score:82,risk_score:.18,state:"green",evidence_ids:["ev_northstar_2023_mix"]},{year:2024,performance_score:87,risk_score:.13,state:"green",evidence_ids:[]},{year:2025,performance_score:90,risk_score:.10,state:"green",evidence_ids:[]}]},
    {company_id:"cmp_hudson",display_name:"Hudson Carton Works (synthetic)",status:"active",comparability_score:.89,trajectory:[
      {year:2016,performance_score:55,risk_score:.45,state:"yellow",evidence_ids:[]},{year:2017,performance_score:59,risk_score:.41,state:"blue",evidence_ids:[]},{year:2018,performance_score:61,risk_score:.39,state:"blue",evidence_ids:[]},{year:2019,performance_score:65,risk_score:.35,state:"blue",evidence_ids:[]},{year:2020,performance_score:42,risk_score:.58,state:"yellow",evidence_ids:["ev_hudson_2020_expansion"]},{year:2021,performance_score:38,risk_score:.62,state:"red",evidence_ids:[]},{year:2022,performance_score:51,risk_score:.49,state:"yellow",evidence_ids:["ev_hudson_2022_restructure"]},{year:2023,performance_score:64,risk_score:.36,state:"blue",evidence_ids:[]},{year:2024,performance_score:69,risk_score:.31,state:"blue",evidence_ids:[]},{year:2025,performance_score:73,risk_score:.27,state:"blue",evidence_ids:[]}]},
    {company_id:"cmp_empire",display_name:"Empire Flex Supply (synthetic)",status:"failed",comparability_score:.87,trajectory:[
      {year:2016,performance_score:63,risk_score:.37,state:"blue",evidence_ids:[]},{year:2017,performance_score:66,risk_score:.34,state:"blue",evidence_ids:[]},{year:2018,performance_score:67,risk_score:.33,state:"blue",evidence_ids:[]},{year:2019,performance_score:65,risk_score:.35,state:"blue",evidence_ids:[]},{year:2020,performance_score:60,risk_score:.40,state:"blue",evidence_ids:[]},{year:2021,performance_score:49,risk_score:.51,state:"yellow",evidence_ids:["ev_empire_2021_customer"]},{year:2022,performance_score:27,risk_score:.73,state:"red",evidence_ids:["ev_empire_2022_loss"]}]},
    {company_id:"cmp_liberty",display_name:"Liberty Wrap Systems (synthetic)",status:"high_performer",comparability_score:.91,trajectory:[
      {year:2016,performance_score:50,risk_score:.50,state:"yellow",evidence_ids:[]},{year:2017,performance_score:57,risk_score:.43,state:"yellow",evidence_ids:[]},{year:2018,performance_score:63,risk_score:.37,state:"blue",evidence_ids:[]},{year:2019,performance_score:70,risk_score:.30,state:"blue",evidence_ids:["ev_liberty_2019_supplier"]},{year:2020,performance_score:72,risk_score:.28,state:"blue",evidence_ids:[]},{year:2021,performance_score:76,risk_score:.24,state:"green",evidence_ids:[]},{year:2022,performance_score:79,risk_score:.21,state:"green",evidence_ids:[]},{year:2023,performance_score:81,risk_score:.19,state:"green",evidence_ids:[]},{year:2024,performance_score:88,risk_score:.12,state:"green",evidence_ids:["ev_liberty_2024_automation"]},{year:2025,performance_score:91,risk_score:.09,state:"green",evidence_ids:[]}]},
    {company_id:"cmp_atlas",display_name:"Atlas Fiber Pack (synthetic)",status:"distressed",comparability_score:.82,trajectory:[
      {year:2016,performance_score:61,risk_score:.39,state:"blue",evidence_ids:[]},{year:2017,performance_score:60,risk_score:.40,state:"blue",evidence_ids:[]},{year:2018,performance_score:58,risk_score:.42,state:"blue",evidence_ids:[]},{year:2019,performance_score:56,risk_score:.44,state:"yellow",evidence_ids:[]},{year:2020,performance_score:54,risk_score:.46,state:"yellow",evidence_ids:[]},{year:2021,performance_score:49,risk_score:.51,state:"yellow",evidence_ids:[]},{year:2022,performance_score:46,risk_score:.54,state:"yellow",evidence_ids:[]},{year:2023,performance_score:43,risk_score:.57,state:"yellow",evidence_ids:[]},{year:2024,performance_score:40,risk_score:.60,state:"yellow",evidence_ids:[]},{year:2025,performance_score:37,risk_score:.63,state:"red",evidence_ids:[]}]}
  ],
  findings:[
    {title:"Validate utilization before adding fixed assets",summary:"The synthetic cohort shows weaker modeled performance when expansion precedes validated utilization, and recovery after asset-light restructuring.",confidence:"evidence_supported_explanation"},
    {title:"Concentration can turn one loss into a survival event",summary:"The failed synthetic company had elevated customer concentration before the modeled loss of its largest contract.",confidence:"evidence_supported_explanation"},
    {title:"Stage investment after demand is demonstrated",summary:"The strongest fixture trajectories pair supplier resilience and delayed capital deployment with sustained utilization.",confidence:"analytical_inference"},
    {title:"Product mix can matter more than category labels",summary:"A higher-margin synthetic product mix is associated with a stronger modeled trajectory.",confidence:"correlation"}
  ],
  lessons:[
    {priority:1,title:"Lease before buying when demand is not validated",action:"Keep the first capacity decision reversible until utilization is demonstrated.",confidence:"evidence_supported_explanation",evidence_ids:["ev_hudson_2020_expansion","ev_hudson_2022_restructure"]},
    {priority:2,title:"Avoid customer concentration",action:"Set concentration limits before one account can determine survival.",confidence:"evidence_supported_explanation",evidence_ids:["ev_empire_2021_customer","ev_empire_2022_loss"]},
    {priority:3,title:"Diversify critical suppliers",action:"Qualify alternatives for high-volatility inputs before a price shock occurs.",confidence:"verified_observation",evidence_ids:["ev_liberty_2019_supplier"]},
    {priority:4,title:"Stage automation after utilization",action:"Tie automation investment to sustained utilization thresholds rather than optimistic forecasts.",confidence:"evidence_supported_explanation",evidence_ids:["ev_liberty_2024_automation"]},
    {priority:5,title:"Track product-mix quality",action:"Measure margin and durability by sub-product rather than treating packaging as one market.",confidence:"correlation",evidence_ids:["ev_northstar_2023_mix"]},
    {priority:6,title:"Protect liquidity during input-cost shocks",action:"Delay discretionary fixed-asset purchases when input costs compress flexibility.",confidence:"analytical_inference",evidence_ids:["ev_northstar_2021_margin"]},
    {priority:7,title:"Treat expansion and demand as one decision",action:"Require demand evidence and utilization thresholds before opening additional capacity.",confidence:"evidence_supported_explanation",evidence_ids:["ev_hudson_2020_expansion"]},
    {priority:8,title:"Use failure cases as first-class evidence",action:"Review failed peers explicitly instead of benchmarking only survivors.",confidence:"verified_observation",evidence_ids:["ev_empire_2022_loss"]},
    {priority:9,title:"Prefer reversible early-stage commitments",action:"Choose leases, pilots, and staged contracts where uncertainty is still high.",confidence:"analytical_inference",evidence_ids:["ev_hudson_2022_restructure","ev_liberty_2024_automation"]},
    {priority:10,title:"Demand evidence for every recommendation",action:"Do not act on a lesson unless its evidence and confidence are visible and acceptable.",confidence:"verified_observation",evidence_ids:["ev_northstar_2021_margin","ev_empire_2022_loss"]}
  ]
};
